
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

/**
 * Interface representing an interactive artifact generated by the AI.
 * Used for displaying tools or content in the ArtifactCard component.
 */
export interface Artifact {
    id: string;
    html: string;
    status: 'streaming' | 'complete';
    styleName: string;
}

export interface Session {
    id: string;
    prompt: string;
    timestamp: number;
    insight?: string;
    artifacts: Artifact[]; // Updated from any[] to ensure type safety for ArtifactCard.tsx
}
